### ISSUE TITLE
test results file isnt generated

### ISSUE THREAD

**Issue by matan-yadgar** [spekt/testlogger#112]
Im running a parent process that prepares a test env (download stuff etc) and then triggers xUnit project (elaboration [here](https://stackoverflow.com/questions/78885392/dotnet-tests-file-generated-only-when-parent-process-exists)). Im waiting for some time (using WaitForExitAsync) as timeout. when the tests are finished (success/fail) within the timeout - the file is generated. However - when the timeout is exceeded - no file is generated. I tried to:

1) add the "--blame-hang-timeout " flag. the file is generated but is empty. no .dmp files are found
2) terminate gracefully with SIGTERM
3) add "xunit,runner.json" config file with "longRunningTestsMs"

I consultedxUnit and they pointed me to either you guys or .NET Core team (https://github.com/xunit/xunit/discussions/3025#discussioncomment-10662664).
 
Am I missing something? How do I make sure that the file is created when the child process times out?

Thanks

**Comment by codito** [comment]
This behavior seems by design and is controlled by the test runner (vstest).

The loggers get an event only when the test completes, either pass/fail/skip. Looks like when the timeout happens in this case, the test runner process is killed, no event is generated and no log gets created.

I am not sure if xunit has a way to mark the test as failed if it exceeds timeout. May be try https://stackoverflow.com/questions/20282111/xunit-net-how-can-i-specify-a-timeout-how-long-a-test-should-maximum-need

The key is to let the runner process run to end and apply timeouts inside the framework or the test itself.
